(()=>{
const M=MT,E=M.esc,I=M.icon,B=M.button,A=M.actions;
const nextId=items=>Math.max(0,...items.map(x=>x.id))+1;
const today=()=>new Date().toISOString().slice(0,10);
const teacherOptions=id=>M.db.teachers.map(t=>`<option value="${t.id}" ${Number(id)===t.id?'selected':''}>${E(t.name)}</option>`).join('');
const subOptions=id=>M.db.subjects.map(s=>`<option value="${s.id}" ${Number(id)===s.id?'selected':''}>${E(s.name)}</option>`).join('');
const form=(kind,body,id='',label='Enregistrer')=>`<form data-form="${kind}" data-id="${id}">${body}${M.formFooter(label)}</form>`;
A['student-form']=el=>{const s=M.student(el?.dataset.id)||{firstName:'',lastName:'',gender:'F',classId:1,status:'Actif',birth:'',parent:'',phone:'',email:'',address:''};M.drawer(s.id?'Modifier le dossier':'Ajouter un élève',form('student',`<div class="form-section"><h3>Informations de l’élève</h3><div class="form-grid">${M.field('Prénom *','firstName',s.firstName,'text','required maxlength="60"')}${M.field('Nom *','lastName',s.lastName,'text','required maxlength="60"')}${M.field('Date de naissance *','birth',s.birth,'date',`required max="${today()}"`)}${M.selectField('Genre','gender','<option value="F" '+(s.gender==='F'?'selected':'')+'>Fille</option><option value="M" '+(s.gender==='M'?'selected':'')+'>Garçon</option>')}${M.selectField('Classe *','classId',M.classOptions(s.classId),'required')}${M.selectField('Statut','status',M.options(['Actif','En attente','Archivé'],s.status))}</div></div><div class="form-section"><h3>Parent ou tuteur</h3><div class="form-grid">${M.field('Nom du parent *','parent',s.parent,'text','required maxlength="80"')}${M.field('Téléphone *','phone',s.phone,'tel','required minlength="8" maxlength="25"')}${M.field('Adresse e-mail','email',s.email,'email','maxlength="100"')}${M.field('Adresse','address',s.address,'text','maxlength="160"')}</div></div>`,s.id||'',s.id?'Enregistrer les modifications':'Créer le dossier'),'Un dossier complet pour bien accompagner chaque élève.');};
M.showStudent=(id,tab='overview')=>{const s=M.student(id);if(!s)return;const paid=M.db.payments.filter(p=>p.studentId===s.id);M.drawer('Dossier de l’élève',`<div class="profile-summary">${M.avatar(M.name(s),s.id,'large')}<div><h3>${E(M.name(s))}</h3><p>${E(s.matricule)} · ${E(M.cls(s.classId)?.name||'Non affecté')}</p>${M.status(s.status)}</div></div><div class="tabs"><button class="tab ${tab==='overview'?'active':''}" data-action="student-tab" data-id="${s.id}" data-tab="overview">Informations</button><button class="tab ${tab==='payments'?'active':''}" data-action="student-tab" data-id="${s.id}" data-tab="payments">Paiements <span class="tab-count">${paid.length}</span></button><button class="tab ${tab==='grades'?'active':''}" data-action="student-tab" data-id="${s.id}" data-tab="grades">Résultats</button></div>${tab==='overview'?`<div class="info-grid"><div><small>Date de naissance</small><b>${M.date(s.birth)}</b></div><div><small>Genre</small><b>${s.gender==='F'?'Fille':'Garçon'}</b></div><div><small>Classe</small><b>${E(M.cls(s.classId)?.name||'Non affecté')}</b></div><div><small>Date d’inscription</small><b>${M.date(s.joined)}</b></div></div><div class="info-section"><h3>Parent / tuteur</h3><div class="contact-row">${I('user')}<b>${E(s.parent)}</b></div><div class="contact-row">${I('phone')}${E(s.phone)}</div><div class="contact-row">${I('mail')}${E(s.email||'Non renseigné')}</div><div class="contact-row">${I('map-pin')}${E(s.address||'Non renseignée')}</div></div><div class="student-balance"><div><small>Solde du trimestre</small><strong>${M.money(M.balance(s))} F</strong></div>${B('Encaisser','payment-form','plus',`data-student="${s.id}"`,'small primary')}</div><div class="form-footer">${B('Modifier le dossier','student-form','pencil',`data-id="${s.id}"`,'')}${B('Bulletin','report','file-text',`data-id="${s.id}"`)}</div>`:tab==='payments'?`${M.table(['RÉFÉRENCE','DATE','MONTANT',''],paid.map(p=>`<tr><td>${E(p.reference)}</td><td>${M.date(p.date)}</td><td class="amount green">${M.money(p.amount)} F</td><td><button class="icon-btn" data-action="receipt" data-id="${p.id}" aria-label="Reçu ${p.reference}">${I('file-text')}</button></td></tr>`),'','Aucun paiement enregistré')}<div class="form-footer">${B('Enregistrer un paiement','payment-form','plus',`data-student="${s.id}"`)}</div>`:`${M.table(['MATIÈRE','MOYENNE / 20'],M.db.subjects.map(sub=>`<tr><td>${E(sub.name)}</td><td class="grade-average">${M.average(s.id,sub.id).toFixed(2)}</td></tr>`))}<div class="report-total"><span>Moyenne générale</span><strong>${M.generalAverage(s.id).toFixed(2)} / 20</strong></div><div class="form-footer">${B('Voir le bulletin','report','file-text',`data-id="${s.id}"`)}</div>`}`);};
A['student-detail']=el=>M.showStudent(el.dataset.id);A['student-tab']=el=>M.showStudent(el.dataset.id,el.dataset.tab);
A['enrollment-form']=()=>M.modal('Nouvelle inscription',form('enrollment',`<div class="notice">${I('user-plus')}<span>Sélectionnez un élève existant. Pour un nouvel élève, créez d’abord son dossier avec le statut « En attente ».</span></div><div class="form-grid">${M.selectField('Élève *','studentId',M.studentOptions(),'required')}${M.selectField('Classe demandée *','classId',M.classOptions(1),'required')}${M.field('Date de demande *','date','2026-03-16','date','required')}</div>`,'','Créer la demande'));
A['enrollment-approve']=el=>{const entry=M.db.enrollments.find(e=>e.id===Number(el.dataset.id));if(!entry||entry.status!=='En attente')return;entry.status='Validée';entry.approvedDate=today();M.student(entry.studentId).status='Actif';M.persist();M.render();M.notify('Inscription validée. Le dossier élève est maintenant actif.');};
A['enrollment-reject']=el=>{const entry=M.db.enrollments.find(e=>e.id===Number(el.dataset.id));if(!entry)return;M.modal('Refuser cette inscription ?',`<p style="font-size:13px;color:var(--muted)">La demande de ${E(M.name(M.student(entry.studentId)))} sera classée comme refusée. Le dossier restera consultable.</p><div class="form-footer"><button class="btn" data-action="close">Annuler</button>${B('Confirmer le refus','reject-confirmed','x',`data-id="${entry.id}"`,'danger')}</div>`);};
A['reject-confirmed']=el=>{const entry=M.db.enrollments.find(e=>e.id===Number(el.dataset.id));entry.status='Refusée';M.student(entry.studentId).status='Archivé';M.persist();M.close();M.render();M.notify('La demande a été refusée.');};
A['teacher-form']=el=>{const t=M.teacher(el?.dataset.id)||{name:'',subject:M.db.subjects[0].name,email:'',phone:''};M.drawer(t.id?'Modifier l’enseignant':'Ajouter un enseignant',form('teacher',`<div class="form-grid">${M.field('Nom complet *','name',t.name,'text','required data-full maxlength="100"')}${M.selectField('Matière principale','subject',M.options(M.db.subjects.map(s=>s.name),t.subject))}${M.field('Téléphone *','phone',t.phone,'tel','required minlength="8" maxlength="25"')}${M.field('Adresse e-mail *','email',t.email,'email','required data-full maxlength="100"')}</div>`,t.id||''));};
A['teacher-detail']=el=>{const t=M.teacher(el.dataset.id);M.drawer('Profil enseignant',`<div class="profile-summary">${M.avatar(t.name,t.id,'large')}<div><h3>${E(t.name)}</h3><p>${E(t.subject)}</p><span class="pill green">Enseignant actif</span></div></div><div class="info-section"><h3>Coordonnées</h3><div class="contact-row">${I('mail')}${E(t.email)}</div><div class="contact-row">${I('phone')}${E(t.phone)}</div></div><div class="info-section"><h3>Classes principales</h3>${M.db.classes.filter(c=>c.teacher===t.id).map(c=>`<button class="btn" data-action="class-students" data-id="${c.id}">${I('school')}${E(c.name)}</button>`).join('')||'<p class="subtitle">Aucune classe principale affectée.</p>'}</div><div class="info-section"><h3>Cours planifiés</h3><p class="subtitle">${M.db.timetable.filter(l=>l.teacherId===t.id).length} cours dans la semaine récurrente.</p></div><div class="form-footer">${B('Modifier le profil','teacher-form','pencil',`data-id="${t.id}"`)}</div>`);};
A['class-form']=el=>{const c=M.cls(el?.dataset.id)||{name:'',cycle:'Élémentaire',capacity:32,teacher:1,room:''};M.modal(c.id?'Modifier la classe':'Nouvelle classe',form('class',`<div class="form-grid">${M.field('Nom de la classe *','name',c.name,'text','required maxlength="35"')}${M.selectField('Cycle','cycle',M.options(['Maternelle','Élémentaire','Collège','Lycée'],c.cycle))}${M.field('Capacité *','capacity',c.capacity,'number','required min="1" max="100" step="1"')}${M.field('Salle *','room',c.room,'text','required maxlength="40"')}${M.selectField('Enseignant principal','teacher',teacherOptions(c.teacher))}</div>`,c.id||''));};
A['subject-form']=el=>{const s=M.subject(el?.dataset.id)||{name:'',coefficient:2,teacher:1};M.modal(s.id?'Modifier la matière':'Nouvelle matière',form('subject',`<div class="form-grid">${M.field('Nom de la matière *','name',s.name,'text','required maxlength="60"')}${M.field('Coefficient *','coefficient',s.coefficient,'number','required min="1" max="10" step="1"')}${M.selectField('Enseignant référent','teacher',teacherOptions(s.teacher))}</div>`,s.id||''));};
A['payment-form']=el=>{const sid=el?.dataset.student;M.modal('Enregistrer un paiement',form('payment',`<div class="form-grid">${M.selectField('Élève *','studentId',M.studentOptions(sid),'required')}${M.selectField('Motif','type',M.options(['Scolarité','Inscription','Cantine','Transport','Études du soir'],'Scolarité'))}${M.field('Montant en FCFA *','amount',sid?Math.min(M.balance(M.student(sid)),50000):50000,'number','required min="1" max="10000000" step="1"')}${M.selectField('Moyen de paiement','method',M.options(['Wave','Espèces','Orange Money','Virement'],'Wave'))}${M.field('Date du paiement *','date','2026-03-16','date','required')}<label class="field full">Note interne<textarea name="notes" maxlength="300" placeholder="Une précision sur ce règlement…"></textarea></label></div>`,'','Enregistrer le paiement'),'Un reçu sera généré après l’enregistrement.');};
M.receiptHTML=p=>{const s=M.student(p.studentId);return `<article class="report-sheet">${M.reportBrand()}<div class="report-heading"><div><h2>Reçu de paiement</h2><small>${E(p.reference)}</small></div><div><b>${M.date(p.date)}</b><br><small>Exemplaire de démonstration</small></div></div><div class="info-grid"><div><small>Reçu de</small><b>${E(s.parent)}</b></div><div><small>Pour l’élève</small><b>${E(M.name(s))}</b></div><div><small>Matricule</small><b>${E(s.matricule)}</b></div><div><small>Classe</small><b>${E(M.cls(s.classId)?.name)}</b></div></div>${M.table(['DÉSIGNATION','MODE DE RÈGLEMENT','MONTANT'],[`<tr><td>${E(p.type)}</td><td>${E(p.method)}</td><td>${M.money(p.amount)} FCFA</td></tr>`])}<div class="report-total"><span>Montant reçu</span><strong>${M.money(p.amount)} FCFA</strong></div><p class="report-footer">Paiement enregistré dans la maquette. Ce document de démonstration n’atteste d’aucune transaction réelle.</p></article>`;};
A.receipt=el=>{const p=M.db.payments.find(x=>x.id===Number(el.dataset.id));if(!p)return;M.modal('Reçu de paiement',M.receiptHTML(p)+`<div class="form-footer">${B('Imprimer / PDF','print-receipt','printer',`data-id="${p.id}"`)}</div>`);};
A['print-receipt']=el=>M.print(M.receiptHTML(M.db.payments.find(p=>p.id===Number(el.dataset.id))));
M.invoiceHTML=s=>`<article class="report-sheet">${M.reportBrand()}<div class="report-heading"><div><h2>Facture de scolarité</h2><small>FAC-2026-${String(s.id).padStart(4,'0')}</small></div><div><b>2ᵉ trimestre</b><br><small>Échéance : 31 mars 2026</small></div></div><div class="info-grid"><div><small>Élève</small><b>${E(M.name(s))}</b></div><div><small>Classe</small><b>${E(M.cls(s.classId)?.name)}</b></div><div><small>Responsable</small><b>${E(s.parent)}</b></div><div><small>Contact</small><b>${E(s.phone)}</b></div></div>${M.table(['DÉSIGNATION','MONTANT'],['<tr><td>Scolarité · 2ᵉ trimestre</td><td>150 000 FCFA</td></tr>',`<tr><td>Versements déjà reçus</td><td>− ${M.money(150000-M.balance(s))} FCFA</td></tr>`])}<div class="report-total"><span>Net à payer</span><strong>${M.money(M.balance(s))} FCFA</strong></div><p class="report-footer">Facture de démonstration · Données fictives.</p></article>`;
A.invoice=el=>{const s=M.student(el.dataset.id);M.modal('Facture de scolarité',M.invoiceHTML(s)+`<div class="form-footer">${B('Imprimer / PDF','print-invoice','printer',`data-id="${s.id}"`,'')}${B('Enregistrer un règlement','payment-form','plus',`data-student="${s.id}"`)}</div>`);};
A['print-invoice']=el=>M.print(M.invoiceHTML(M.student(el.dataset.id)));
M.reportHTML=s=>`<article class="report-sheet">${M.reportBrand()}<div class="report-heading"><div><h2>Bulletin scolaire</h2><small>${M.view.term}${M.view.term==='1'?'er':'e'} trimestre · ${E(M.db.years.find(y=>y.active)?.name)}</small></div><div><b>${E(M.name(s))}</b><br><small>${E(s.matricule)} · ${E(M.cls(s.classId)?.name)}</small></div></div>${M.table(['MATIÈRE','COEFF.','DEVOIR','COMPO.','MOYENNE'],M.db.subjects.map(sub=>`<tr><td>${E(sub.name)}</td><td>${sub.coefficient}</td><td>${M.grade(s.id,sub.id,'test')}</td><td>${M.grade(s.id,sub.id,'exam')}</td><td class="grade-average">${M.average(s.id,sub.id).toFixed(2)}</td></tr>`))}<div class="report-total"><span>Moyenne générale</span><strong>${M.generalAverage(s.id).toFixed(2)} / 20</strong></div><div class="info-grid"><div><small>Appréciation du conseil</small><b>${M.generalAverage(s.id)>=14?'Bon travail. Continuez vos efforts.':'Des progrès à poursuivre avec régularité.'}</b></div><div><small>Direction de l’établissement</small><b>Mère Teresa</b></div></div><p class="report-footer">Bulletin de démonstration · Notes fictives · Moyenne générale pondérée par les coefficients.</p></article>`;
A.report=el=>{const s=M.student(el.dataset.id);M.modal('Bulletin scolaire',M.reportHTML(s)+`<div class="form-footer">${B('Imprimer / PDF','print-report','printer',`data-id="${s.id}"`)}</div>`);};
A['print-report']=el=>M.print(M.reportHTML(M.student(el.dataset.id)));
A['enrollment-certificate']=el=>{const entry=M.db.enrollments.find(e=>e.id===Number(el.dataset.id));if(!entry||entry.status!=='Validée')return;const s=M.student(entry.studentId);M.certificate=`<article class="report-sheet">${M.reportBrand()}<h2 style="text-align:center;margin:35px 0">Attestation d’inscription</h2><p style="font-size:14px;line-height:2.2">La direction de ${E(M.db.settings.school)} atteste que <b>${E(M.name(s))}</b>, matricule <b>${E(s.matricule)}</b>, est inscrit(e) en classe de <b>${E(M.cls(s.classId)?.name)}</b> pour l’année scolaire <b>${E(M.db.years.find(y=>y.active)?.name)}</b>.</p><p style="margin:30px 0">Inscription validée le ${M.date(entry.approvedDate||entry.date)}.</p><p class="report-footer">Attestation de démonstration · Données fictives.</p></article>`;M.modal('Attestation d’inscription',M.certificate+`<div class="form-footer">${B('Imprimer / PDF','print-certificate','printer')}</div>`);};A['print-certificate']=()=>M.print(M.certificate);
A['subscription-form']=()=>{const type=['Cantine','Transport','Études du soir'].indexOf(M.view.service);M.modal('Nouvel abonnement',form('subscription',`<div class="form-grid">${M.selectField('Élève *','studentId',M.studentOptions(),'required')}${M.selectField('Service','service',M.options(['Cantine','Transport','Études du soir'],M.view.service))}${M.field('Formule *','plan',['Déjeuner · 5 jours','Circuit Dakar centre','Lundi, mardi et jeudi'][type],'text','required maxlength="100"')}${M.field('Mensualité en FCFA *','amount',[25000,30000,15000][type],'number','required min="1" max="1000000" step="1"')}</div>`,'','Créer l’abonnement'));};
A['subscription-toggle']=el=>{const s=M.db.subscriptions.find(s=>s.id===Number(el.dataset.id));s.status=s.status==='Actif'?'Suspendu':'Actif';M.persist();M.render();M.notify(s.status==='Actif'?'Abonnement réactivé.':'Abonnement suspendu.');};
A['lesson-form']=el=>{const l=M.db.timetable.find(l=>l.id===Number(el?.dataset.id))||{classId:M.view.scheduleClass,day:Number(el?.dataset.day||0),start:Number(el?.dataset.hour||8),end:Number(el?.dataset.hour||8)+2,subjectId:1,teacherId:1,room:M.cls(M.view.scheduleClass)?.room||''};M.modal(l.id?'Modifier le cours':'Ajouter un cours',form('lesson',`<div class="form-grid">${M.selectField('Classe','classId',M.classOptions(l.classId))}${M.selectField('Matière','subjectId',subOptions(l.subjectId))}${M.selectField('Enseignant','teacherId',teacherOptions(l.teacherId))}${M.selectField('Jour','day',['Lundi','Mardi','Mercredi','Jeudi','Vendredi'].map((d,i)=>`<option value="${i}" ${l.day===i?'selected':''}>${d}</option>`).join(''))}${M.selectField('Créneau de 2 heures','start',[8,10,14,16].map(h=>`<option value="${h}" ${l.start===h?'selected':''}>${h}:00 – ${h+2}:00</option>`).join(''))}${M.field('Salle *','room',l.room,'text','required maxlength="40"')}</div>${l.id?`<div style="margin-top:20px">${B('Supprimer ce cours','lesson-delete','trash',`data-id="${l.id}"`,'small danger')}</div>`:''}`,l.id||''));};
A.lesson=el=>A['lesson-form'](el);A.slot=(el,e)=>{if(!e.target.closest('.lesson'))A['lesson-form'](el);};
A['lesson-delete']=el=>{M.db.timetable=M.db.timetable.filter(l=>l.id!==Number(el.dataset.id));M.persist();M.close();M.render();M.notify('Cours retiré du planning.');};
A['year-form']=el=>{const y=M.db.years.find(y=>y.id===Number(el?.dataset.id))||{name:'',start:'2026-10-01',end:'2027-07-31'};M.modal(y.id?'Modifier l’année':'Nouvelle année scolaire',form('year',`<div class="form-grid">${M.field('Libellé *','name',y.name,'text','required data-full placeholder="2026 – 2027" maxlength="30"')}${M.field('Date de début *','start',y.start,'date','required')}${M.field('Date de fin *','end',y.end,'date','required')}</div>`,y.id||''));};
A['year-activate']=el=>{M.db.years.forEach(y=>y.active=y.id===Number(el.dataset.id));M.persist();M.render();M.notify('L’année scolaire active a été mise à jour.');};
A['save-grades']=()=>{const inputs=[...document.querySelectorAll('[data-grade]')];const invalid=inputs.find(i=>i.value===''||!i.checkValidity());if(invalid){invalid.focus();M.notify('Chaque note doit être comprise entre 0 et 20, par pas de 0,25.',true);return;}inputs.forEach(i=>M.db.grades[`${i.dataset.student}-${M.view.subject}-${M.view.term}-${i.dataset.grade}`]=Number(i.value));M.persist();M.render();M.notify('Notes enregistrées. Les bulletins sont à jour.');};
document.addEventListener('input',e=>{const el=e.target;if(!el.matches('[data-grade]'))return;const tr=el.closest('tr');const a=tr.querySelector('[data-grade="test"]'),b=tr.querySelector('[data-grade="exam"]');if(a.value!==''&&b.value!==''&&a.checkValidity()&&b.checkValidity()){const avg=(Number(a.value)+Number(b.value)*2)/3;tr.querySelector('[data-average]').textContent=avg.toFixed(2);tr.querySelector('[data-appreciation]').innerHTML=M.status(avg>=16?'Très bien':avg>=14?'Bien':avg>=10?'Assez bien':'À renforcer');}});
A.profile=()=>M.drawer('Mon profil',`<div class="profile-summary">${M.avatar('Administration Direction',0,'large')}<div><h3>Administration</h3><p>Direction de l’établissement</p><span class="pill blue">Administrateur</span></div></div><div class="info-section"><h3>Établissement</h3><p class="subtitle">${E(M.db.settings.school)}</p><div class="contact-row" style="margin-top:18px">${I('map-pin')}${E(M.db.settings.city)}</div></div><div class="notice" style="margin-top:22px">${I('shield-check')}<span>Profil de démonstration. La connexion et les droits d’accès seront raccordés à Laravel lors de l’intégration.</span></div><div class="form-footer">${B('Paramètres','open-settings','settings')}</div>`);
A.school=()=>{M.view.settingsTab='school';M.navigate('settings');};A['open-settings']=()=>{M.$('#drawer').close();M.view.settingsTab='school';M.navigate('settings');};
A.notifications=()=>{const n=M.db.enrollments.filter(e=>e.status==='En attente').length;M.drawer('Notifications',`<div class="notification-item"><span>${I('user-plus')}</span><div><h3>${n} inscriptions en attente</h3><p>Les nouveaux dossiers attendent votre validation.</p><button class="text-btn" data-action="notification-route" data-route="enrollments">Consulter les dossiers ${I('arrow-right')}</button></div></div><div class="notification-item"><span>${I('receipt')}</span><div><h3>Échéance des scolarités</h3><p>Le règlement du 2ᵉ trimestre est prévu pour le 31 mars 2026.</p><button class="text-btn" data-action="notification-route" data-route="billing">Consulter les comptes ${I('arrow-right')}</button></div></div><div class="notification-item"><span>${I('calendar-week')}</span><div><h3>Votre planning hebdomadaire</h3><p>Les cours de la semaine sont disponibles dans l’emploi du temps.</p><button class="text-btn" data-action="notification-route" data-route="timetable">Ouvrir le planning ${I('arrow-right')}</button></div></div><div class="form-footer">${B('Tout marquer comme lu','notifications-read','check','','')}</div>`,'Les points à suivre dans votre établissement.');};
A['notifications-read']=()=>{M.db.notificationsRead=true;M.persist();M.$('#drawer').close();M.render();M.notify('Toutes les notifications sont marquées comme lues.');};A['notification-route']=el=>{M.$('#drawer').close();M.navigate(el.dataset.route);};
M.commandResults=query=>{const q=query.toLocaleLowerCase('fr').trim();const pages=M.nav.flatMap(g=>g.items).concat([['settings','Paramètres','settings']]).filter(p=>p[1].toLocaleLowerCase('fr').includes(q));const students=q?M.db.students.filter(s=>(M.name(s)+' '+s.matricule).toLocaleLowerCase('fr').includes(q)).slice(0,6):[];return `${pages.length?'<div class="command-title">PAGES</div>':''}${pages.slice(0,7).map(([route,label,icon])=>`<button class="command-item" data-action="command-route" data-route="${route}"><span>${I(icon)}</span><span>${label}</span><span>${I('arrow-right')}</span></button>`).join('')}${students.length?'<div class="command-title">ÉLÈVES</div>':''}${students.map(s=>`<button class="command-item" data-action="command-student" data-id="${s.id}">${M.avatar(M.name(s),s.id)}<span>${E(M.name(s))}<small>${E(s.matricule)} · ${E(M.cls(s.classId)?.name)}</small></span><span>${I('arrow-up-right')}</span></button>`).join('')}${pages.length||students.length?'':M.empty('Aucun résultat','Essayez le nom, le matricule ou une page.')}`;};
A.search=()=>{const d=M.$('#command');d.innerHTML=`<div class="command-search"><span>${I('search')}</span><input id="command-input" placeholder="Rechercher un élève, une page…" aria-label="Recherche globale" autocomplete="off"><button class="icon-btn" data-action="command-close" aria-label="Fermer la recherche"><kbd>ESC</kbd></button></div><div class="command-results">${M.commandResults('')}</div><div class="table-foot"><span>↑ ↓ pour naviguer</span><span>Entrée pour ouvrir</span></div>`;d.showModal();M.$('#command-input').focus();};
A['command-route']=el=>{M.$('#command').close();M.navigate(el.dataset.route);};A['command-student']=el=>{M.$('#command').close();M.navigate('students');M.showStudent(el.dataset.id);};A['command-close']=()=>M.$('#command').close();
document.addEventListener('input',e=>{if(e.target.id==='command-input')M.$('.command-results').innerHTML=M.commandResults(e.target.value);});
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();if(M.$('#command').open)M.$('#command').close();else A.search();}if(M.$('#command').open&&['ArrowDown','ArrowUp','Enter'].includes(e.key)){const items=[...M.$('#command').querySelectorAll('.command-item')];if(!items.length)return;const idx=items.indexOf(document.activeElement);if(e.key==='ArrowDown'){e.preventDefault();items[Math.min(idx+1,items.length-1)].focus();}if(e.key==='ArrowUp'){e.preventDefault();idx>0?items[idx-1].focus():M.$('#command-input').focus();}if(e.key==='Enter'&&document.activeElement.id==='command-input'){e.preventDefault();items[0].click();}}});
A['export-selected']=()=>{const rows=M.db.students.filter(s=>M.view.selected.has(s.id));M.csv('mere-teresa-selection',['Matricule','Élève','Classe','Statut'],rows.map(s=>[s.matricule,M.name(s),M.cls(s.classId)?.name,s.status]));};
A['reset-confirm']=()=>M.modal('Réinitialiser la démonstration ?',`<p style="font-size:13px;color:var(--muted);line-height:1.8">Les élèves ajoutés, paiements, notes et préférences de cette maquette seront remplacés par les données initiales. Le projet Laravel n’est pas concerné.</p><div class="form-footer"><button class="btn" data-action="close">Annuler</button>${B('Réinitialiser','reset','refresh','','danger')}</div>`);
A.reset=()=>{M.reset();M.close();M.view.selected.clear();M.navigate('dashboard');M.notify('La démonstration a été réinitialisée.');};
let draggedWidget=null,draggedLesson=null;
document.addEventListener('dragstart',e=>{const w=e.target.closest('[data-drag-widget]');const l=e.target.closest('[data-drag-lesson]');if(w){draggedWidget=w.dataset.dragWidget;e.dataTransfer.setData('text/plain',draggedWidget);e.dataTransfer.effectAllowed='move';e.dataTransfer.setDragImage(w.closest('.widget'),40,25);w.closest('.widget').classList.add('dragging');}if(l){draggedLesson=Number(l.dataset.dragLesson);e.dataTransfer.setData('text/plain',String(draggedLesson));e.dataTransfer.effectAllowed='move';}});
document.addEventListener('dragover',e=>{const target=draggedWidget?e.target.closest('[data-widget-id]'):draggedLesson?e.target.closest('[data-drop-day]'):null;if(target){e.preventDefault();target.classList.add('drag-over');e.dataTransfer.dropEffect='move';}});
document.addEventListener('dragleave',e=>{const target=e.target.closest('.drag-over');if(target&&!target.contains(e.relatedTarget))target.classList.remove('drag-over');});
document.addEventListener('drop',e=>{if(draggedWidget){const target=e.target.closest('[data-widget-id]');if(target){e.preventDefault();const dest=target.dataset.widgetId;const group=id=>['revenue','enrollments','distribution'].includes(id);if(group(dest)!==group(draggedWidget)){M.notify('Déplacez ce widget dans la même colonne.',true);}else if(dest!==draggedWidget){const from=M.db.widgets.indexOf(draggedWidget),to=M.db.widgets.indexOf(dest);M.db.widgets.splice(from,1);M.db.widgets.splice(to,0,draggedWidget);M.persist();M.render();M.notify('Organisation du tableau de bord enregistrée.');}}}if(draggedLesson){const target=e.target.closest('[data-drop-day]');if(target){e.preventDefault();const l=M.db.timetable.find(x=>x.id===draggedLesson);const day=Number(target.dataset.dropDay),start=Number(target.dataset.dropHour);if(M.db.timetable.some(x=>x.id!==l.id&&(x.classId===l.classId||x.teacherId===l.teacherId||x.room===l.room)&&x.day===day&&x.start===start)){M.notify('Créneau indisponible pour cette classe, cet enseignant ou cette salle.',true);}else{l.day=day;l.start=start;l.end=start+2;M.persist();M.render();M.notify('Le cours a été déplacé.');}}}draggedWidget=null;draggedLesson=null;document.querySelectorAll('.drag-over,.dragging').forEach(el=>el.classList.remove('drag-over','dragging'));});
document.addEventListener('dragend',()=>{draggedWidget=null;draggedLesson=null;document.querySelectorAll('.drag-over,.dragging').forEach(el=>el.classList.remove('drag-over','dragging'));});
M.forms={
student:(values,id)=>{const classId=Number(values.classId);const c=M.cls(classId);const original=M.student(id);if(c&&M.db.students.filter(s=>s.classId===classId&&s.id!==id).length>=c.capacity)throw Error('Cette classe a atteint sa capacité. Choisissez une autre classe.');const rec={...values,classId};if(!rec.firstName.trim()||!rec.lastName.trim()||!rec.parent.trim())throw Error('Le prénom, le nom et le parent ne peuvent pas être vides.');if(original)Object.assign(original,rec);else{rec.id=nextId(M.db.students);rec.matricule=`MT-25-${String(rec.id).padStart(4,'0')}`;rec.joined=today();M.db.students.push(rec);}const sid=original?.id||rec.id;if(rec.status==='En attente'&&!M.db.enrollments.some(e=>e.studentId===sid&&e.status==='En attente'))M.db.enrollments.push({id:nextId(M.db.enrollments),studentId:sid,date:today(),status:'En attente'});M.db.enrollments.filter(e=>e.studentId===sid&&e.status==='En attente').forEach(e=>{if(rec.status==='Actif'){e.status='Validée';e.approvedDate=today();}if(rec.status==='Archivé')e.status='Refusée';});return original?'Le dossier élève a été mis à jour.':'Le dossier élève a été créé.';},
enrollment:(v)=>{const sid=Number(v.studentId);if(M.db.enrollments.some(e=>e.studentId===sid&&['En attente','Validée'].includes(e.status)))throw Error('Cet élève possède déjà une demande en attente ou validée.');const c=M.cls(v.classId);if(M.db.students.filter(s=>s.classId===c.id&&s.id!==sid).length>=c.capacity)throw Error('Cette classe est complète.');M.db.enrollments.push({id:nextId(M.db.enrollments),studentId:sid,date:v.date,status:'En attente'});Object.assign(M.student(sid),{classId:Number(v.classId),status:'En attente'});return'La demande d’inscription a été créée.';},
teacher:(v,id)=>{const rec=M.teacher(id);if(!v.name.trim())throw Error('Veuillez saisir le nom de l’enseignant.');if(rec)Object.assign(rec,v);else M.db.teachers.push({...v,id:nextId(M.db.teachers),status:'Actif'});return'Le profil enseignant a été enregistré.';},
class:(v,id)=>{if(M.db.classes.some(c=>c.id!==id&&c.name.toLowerCase()===v.name.toLowerCase().trim()))throw Error('Une classe porte déjà ce nom.');const capacity=Number(v.capacity);if(M.db.students.filter(s=>s.classId===id).length>capacity)throw Error('La capacité ne peut pas être inférieure à l’effectif actuel.');const rec={...v,capacity,teacher:Number(v.teacher)};if(id)Object.assign(M.cls(id),rec);else M.db.classes.push({...rec,id:nextId(M.db.classes)});return'La classe a été enregistrée.';},
subject:(v,id)=>{if(M.db.subjects.some(s=>s.id!==id&&s.name.toLowerCase()===v.name.toLowerCase().trim()))throw Error('Cette matière existe déjà.');const rec={...v,coefficient:Number(v.coefficient),teacher:Number(v.teacher)};if(id)Object.assign(M.subject(id),rec);else M.db.subjects.push({...rec,id:nextId(M.db.subjects)});return'La matière a été enregistrée.';},
payment:(v)=>{const sid=Number(v.studentId),amount=Number(v.amount);if(v.type==='Scolarité'&&amount>M.balance(M.student(sid)))throw Error(`Le montant dépasse le solde de scolarité (${M.money(M.balance(M.student(sid)))} FCFA).`);const id=nextId(M.db.payments);M.db.payments.push({...v,studentId:sid,amount,id,reference:`REC-2026-${String(id).padStart(4,'0')}`});M.lastPayment=id;return'Paiement enregistré. Le reçu est prêt.';},
subscription:(v)=>{const sid=Number(v.studentId);if(M.db.subscriptions.some(s=>s.studentId===sid&&s.service===v.service))throw Error('Cet élève possède déjà un abonnement à ce service.');M.db.subscriptions.push({...v,id:nextId(M.db.subscriptions),studentId:sid,amount:Number(v.amount),status:'Actif'});M.view.service=v.service;return'L’abonnement a été créé.';},
lesson:(v,id)=>{const rec={...v,classId:Number(v.classId),day:Number(v.day),start:Number(v.start),end:Number(v.start)+2,subjectId:Number(v.subjectId),teacherId:Number(v.teacherId)};if(M.db.timetable.some(l=>l.id!==id&&l.classId===rec.classId&&l.day===rec.day&&l.start===rec.start))throw Error('Cette classe a déjà un cours sur ce créneau.');if(M.db.timetable.some(l=>l.id!==id&&l.teacherId===rec.teacherId&&l.day===rec.day&&l.start===rec.start))throw Error('Cet enseignant a déjà un cours sur ce créneau.');if(M.db.timetable.some(l=>l.id!==id&&l.room===rec.room&&l.day===rec.day&&l.start===rec.start))throw Error('Cette salle est déjà occupée sur ce créneau.');if(id)Object.assign(M.db.timetable.find(l=>l.id===id),rec);else M.db.timetable.push({...rec,id:nextId(M.db.timetable)});M.view.scheduleClass=rec.classId;return'Le cours a été enregistré.';},
year:(v,id)=>{if(v.end<=v.start)throw Error('La fin de l’année doit être postérieure à son début.');if(M.db.years.some(y=>y.id!==id&&y.name===v.name.trim()))throw Error('Cette année existe déjà.');if(id)Object.assign(M.db.years.find(y=>y.id===id),v);else M.db.years.unshift({...v,id:nextId(M.db.years),active:false});return'L’année scolaire a été enregistrée.';},
settings:(v)=>{Object.assign(M.db.settings,v);return'Les informations de l’établissement ont été enregistrées.';}
};
document.addEventListener('submit',e=>{const f=e.target.closest('form[data-form]');if(!f)return;e.preventDefault();if(!f.reportValidity())return;const values=Object.fromEntries(new FormData(f));Object.keys(values).forEach(k=>{if(typeof values[k]==='string')values[k]=values[k].trim();});try{const message=M.forms[f.dataset.form](values,Number(f.dataset.id)||undefined);M.persist();if(f.closest('dialog'))f.closest('dialog').close();M.render();M.notify(message);if(f.dataset.form==='payment'){if(M.$('#drawer').open)M.showStudent(Number(values.studentId));A.receipt({dataset:{id:M.lastPayment}});}}catch(error){const field=f.querySelector('.form-error');field.hidden=false;field.textContent=error.message;}});
})();
