window.MT = window.MT || {};
(()=>{
const key='mere-teresa-template-v1';
const first=['Aminata','Moussa','Fatou','Ibrahima','Mariama','Ousmane','Aïssatou','Abdoulaye','Sokhna','Cheikh','Khady','Mamadou','Ndeye','Seydou','Adama','Aliou','Coumba','Pape','Binta','Ismaïla','Rokhaya','Lamine','Awa','Amadou'];
const last=['Ndiaye','Diop','Fall','Sarr','Ba','Sow','Gueye','Diallo','Faye','Seck','Cissé','Thiam'];
const classNames=['Petite section','Grande section','CP','CE1','CE2','CM1','CM2','6ème A','5ème A','4ème A','3ème A','Seconde S'];
function seed(){
 const teachers=['Sophie Diouf','Mamadou Sy','Awa Sarr','Jean-Pierre Faye','Fatou Diagne','Omar Ndiaye','Marie Sène','Ibrahima Kane','Aïssatou Ba','Cheikh Diop','Anne-Marie Fall','Ousmane Cissé','Binta Sow','Paul Samb','Mariama Thiam','Abdou Seck','Khady Diallo','Alioune Gueye'].map((name,i)=>({id:i+1,name,subject:['Français','Mathématiques','Anglais','Histoire-Géographie','Sciences','Éducation physique'][i%6],email:`enseignant${i+1}@example.test`,phone:`77 000 ${String(i+1).padStart(2,'0')} 00`,status:'Actif'}));
 const classes=classNames.map((name,i)=>({id:i+1,name,cycle:i<2?'Maternelle':i<7?'Élémentaire':i<11?'Collège':'Lycée',capacity:32,teacher:i+1,room:`Salle ${String(i+1).padStart(2,'0')}`}));
 const students=Array.from({length:288},(_,i)=>({id:i+1,matricule:`MT-25-${String(i+1).padStart(4,'0')}`,firstName:first[i%24],lastName:last[(Math.floor(i/24)+i)%12],classId:Math.floor(i/24)+1,gender:i%2?'M':'F',birth:`${2019-Math.floor(i/24)}-${String(i%12+1).padStart(2,'0')}-${String(i%27+1).padStart(2,'0')}`,parent:`${i%2?'Mme':'M.'} ${last[(Math.floor(i/24)+i)%12]}`,phone:`77 000 ${String(Math.floor(i/100)).padStart(2,'0')} ${String(i%100).padStart(2,'0')}`,email:`parent${i+1}@example.test`,address:'Dakar, Sénégal',status:i>281?'En attente':'Actif',joined:`2025-10-${String(i%25+1).padStart(2,'0')}`}));
 const payments=Array.from({length:84},(_,i)=>({id:i+1,studentId:i%72+1,amount:[45000,50000,55000,35000][i%4],method:['Wave','Espèces','Orange Money','Virement'][i%4],type:i%7===0?'Inscription':'Scolarité',date:`2026-0${i<20?1:i<50?2:3}-${String(i%22+1).padStart(2,'0')}`,reference:`REC-2026-${String(i+1).padStart(4,'0')}`}));
 const subjects=['Français','Mathématiques','Anglais','Histoire-Géographie','Sciences','Éducation physique'].map((name,i)=>({id:i+1,name,coefficient:[4,4,3,2,3,1][i],teacher:i+1}));
 const subscriptions=Array.from({length:36},(_,i)=>({id:i+1,studentId:i+1,service:['Cantine','Transport','Études du soir'][i%3],plan:['Déjeuner · 5 jours','Circuit Dakar centre','Lundi, mardi et jeudi'][i%3],amount:[25000,30000,15000][i%3],status:i%9===0?'Suspendu':'Actif'}));
 const timetable=[];for(let c=1;c<=12;c++)for(let d=0;d<5;d++)for(let t=0;t<3;t++)timetable.push({id:timetable.length+1,classId:c,day:d,start:[8,10,14][t],end:[10,12,16][t],subjectId:(d+t)%6+1,teacherId:c,room:classes[c-1].room});
 return {version:1,students,teachers,classes,payments,subjects,subscriptions,timetable,grades:{},enrollments:students.slice(-6).map((s,i)=>({id:i+1,studentId:s.id,date:`2026-03-${String(9+i).padStart(2,'0')}`,status:'En attente'})),years:[{id:1,name:'2025 – 2026',start:'2025-10-01',end:'2026-07-31',active:true},{id:2,name:'2024 – 2025',start:'2024-10-01',end:'2025-07-31',active:false}],widgets:['revenue','enrollments','activity','collections','agenda'],settings:{school:'Groupe Scolaire Mère Teresa',city:'Dakar, Sénégal',email:'contact@example.test',phone:'33 000 00 00',address:'Dakar, Sénégal',theme:'light',compact:false},notificationsRead:false};
}
let state;try{state=JSON.parse(localStorage.getItem(key));if(state?.version!==1)state=null;}catch{}state=state||seed();
MT.db=state;MT.seed=seed;MT.save=()=>{try{localStorage.setItem(key,JSON.stringify(MT.db));return true;}catch{document.querySelector('#save-status').textContent='Session non sauvegardée';return false;}};MT.reset=()=>{MT.db=seed();MT.save();};
MT.view={route:'dashboard',query:'',filter:'Tous',page:1,sort:'name',direction:1,selected:new Set(),period:'mars',service:'Cantine',gradeClass:8,subject:1,term:'2',scheduleClass:8,week:0,profileTab:'overview'};
MT.nav=[{label:'VUE D’ENSEMBLE',items:[['dashboard','Tableau de bord','layout-dashboard']]},{label:'SCOLARITÉ',items:[['students','Élèves','users'],['enrollments','Inscriptions','user-plus'],['classes','Classes & matières','school'],['teachers','Enseignants','chalkboard'],['timetable','Emploi du temps','calendar-week'],['grades','Notes & bulletins','report-analytics']]},{label:'FINANCES & SERVICES',items:[['finance','Vue financière','chart-pie'],['payments','Paiements','wallet'],['billing','Scolarités & factures','receipt'],['services','Services scolaires','bus']]},{label:'ÉTABLISSEMENT',items:[['years','Années scolaires','calendar-event']]}];
})();
